version: "1.0"
services:
  get:
    build: ./service-1
    restart: always
    ports:
      - "5000:5000"
    environment:
      MONGO_PORT: 27017
      APP_PORT: 5000

  post:
    build: ./service-2
    restart: always
    ports:
      - "8000:8000"
    environment:
      MONGO_PORT: 27017
      APP_PORT: 8000

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      PUID: 1000
      PGID: 1000